CREATE TABLE Pais (
    id_pais NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    habitantes NUMBER,
    area_km2 NUMBER
);

CREATE TABLE Grupo_Terrorista (
    id_grupo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    fecha_origen DATE,
    tiempo_funcionamiento NUMBER,
    id_pais NUMBER NOT NULL,
    CONSTRAINT fk_grupo_pais
        FOREIGN KEY (id_pais) REFERENCES Pais(id_pais)
);

CREATE TABLE Persona (
    id_persona NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    fecha_nacimiento DATE,
    nacionalidad VARCHAR2(100)
);

/* =========================
   LIDER PRINCIPAL
   ========================= */

CREATE TABLE Lider_Principal (
    id_grupo NUMBER PRIMARY KEY,
    id_persona NUMBER UNIQUE,
    fecha_inicio DATE,
    CONSTRAINT fk_lider_grupo
        FOREIGN KEY (id_grupo) REFERENCES Grupo_Terrorista(id_grupo),
    CONSTRAINT fk_lider_persona
        FOREIGN KEY (id_persona) REFERENCES Persona(id_persona)
);

/* =========================
   INTEGRANTES DE GRUPOS
   ========================= */

CREATE TABLE Integrante_Grupo (
    id_persona NUMBER,
    id_grupo NUMBER,
    fecha_ingreso DATE NOT NULL,
    PRIMARY KEY (id_persona, id_grupo),
    CONSTRAINT fk_int_persona
        FOREIGN KEY (id_persona) REFERENCES Persona(id_persona),
    CONSTRAINT fk_int_grupo
        FOREIGN KEY (id_grupo) REFERENCES Grupo_Terrorista(id_grupo)
);

/* =========================
   ATENTADOS (GENERAL)
   ========================= */

CREATE TABLE Atentado (
    id_grupo NUMBER,
    codigo_atentado NUMBER,
    fecha DATE NOT NULL,
    descripcion VARCHAR2(500),
    tipo VARCHAR2(20) CHECK (tipo IN ('AEREO','MARITIMO')),
    PRIMARY KEY (id_grupo, codigo_atentado),
    CONSTRAINT fk_atentado_grupo
        FOREIGN KEY (id_grupo) REFERENCES Grupo_Terrorista(id_grupo)
);

/* =========================
   ATENTADOS AEREOS
   ========================= */

CREATE TABLE Avion (
    id_avion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca VARCHAR2(100),
    modelo VARCHAR2(100),
    capacidad NUMBER
);

CREATE TABLE Atentado_Aereo (
    id_grupo NUMBER,
    codigo_atentado NUMBER,
    pies_altura NUMBER,
    id_avion NUMBER,
    PRIMARY KEY (id_grupo, codigo_atentado),
    CONSTRAINT fk_aereo_atentado
        FOREIGN KEY (id_grupo, codigo_atentado)
        REFERENCES Atentado(id_grupo, codigo_atentado),
    CONSTRAINT fk_aereo_avion
        FOREIGN KEY (id_avion) REFERENCES Avion(id_avion)
);

/* =========================
   ATENTADOS MARITIMOS
   ========================= */

CREATE TABLE Oceano (
    id_oceano NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    extension_km2 NUMBER
);

CREATE TABLE Atentado_Maritimo (
    id_grupo NUMBER,
    codigo_atentado NUMBER,
    tipo_navio VARCHAR2(100),
    id_oceano NUMBER,
    PRIMARY KEY (id_grupo, codigo_atentado),
    CONSTRAINT fk_maritimo_atentado
        FOREIGN KEY (id_grupo, codigo_atentado)
        REFERENCES Atentado(id_grupo, codigo_atentado),
    CONSTRAINT fk_maritimo_oceano
        FOREIGN KEY (id_oceano) REFERENCES Oceano(id_oceano)
);

/* =========================
   FALLECIDOS EN ATENTADOS
   ========================= */

CREATE TABLE Fallecido (
    id_fallecido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150),
    nacionalidad VARCHAR2(100)
);

CREATE TABLE Fallecido_Atentado (
    id_fallecido NUMBER,
    id_grupo NUMBER,
    codigo_atentado NUMBER,
    PRIMARY KEY (id_fallecido, id_grupo, codigo_atentado),
    CONSTRAINT fk_fall_persona
        FOREIGN KEY (id_fallecido) REFERENCES Fallecido(id_fallecido),
    CONSTRAINT fk_fall_atentado
        FOREIGN KEY (id_grupo, codigo_atentado)
        REFERENCES Atentado(id_grupo, codigo_atentado)
);

/* =========================
   PARTICIPACION DE INTEGRANTES EN ATENTADOS
   ========================= */

CREATE TABLE Participacion_Atentado (
    id_persona NUMBER,
    id_grupo NUMBER,
    codigo_atentado NUMBER,
    PRIMARY KEY (id_persona, id_grupo, codigo_atentado),
    CONSTRAINT fk_part_persona
        FOREIGN KEY (id_persona) REFERENCES Persona(id_persona),
    CONSTRAINT fk_part_atentado
        FOREIGN KEY (id_grupo, codigo_atentado)
        REFERENCES Atentado(id_grupo, codigo_atentado)
);
